name: Deploy React to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build project
      env:
        VITE_FACTORY_ALERT_MODE: socketio
        VITE_FACTORY_ALERT_URL: https://socket.sukalyanai.com
        VITE_FACTORY_SOCKET_TOKEN: ${{ secrets.SOCKET_IO_TOKEN }}
      run: npm run build

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        local-dir: dist/
        server-dir: /public_html/
